server:
  port: 8080

spring:
  application:
    name: popcorn-palace
  datasource:
    url: jdbc:postgresql://localhost:5432/popcorn-palace
    username: popcorn-palace
    password: popcorn-palace
    driverClassName: org.postgresql.Driver
    platform: postgres
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  # jpa:
  #   # database-platform: org.hibernate.dialect.PostgreSQLDialect
  #   show-sql: true
  #   hibernate:
  #     ddl-auto: update  # Adjust as needed (e.g., validate, create-drop)
  #   properties:
  #     hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect  # Explicit Hibernate dialect
  #       # hbm2ddl.auto: update
  #   # generate-ddl: true
        # 
  sql:
    init:
      mode: always